#!/bin/bash
banner "YaSg"
FILE_NAME='file.htm'
exvars=0
exfuncs=0
exvars=0
allfuncs=0
enable_desc=0
enable_out_file=0
description=""
function get_user_func {
        #echo "<?include('$i');echo '#####';print_r(get_defined_vars());?>"|php5
    php -r "include('$file');
        \$a=get_defined_functions();
        \$isempty=0;
        foreach(\$a['user'] as \$row){
            file_put_contents('$FILE_NAME',\$row.'<br>',FILE_APPEND);
            \$isempty=1;
        }
        if(\$isempty==0)
            file_put_contents('$FILE_NAME','None<br>',FILE_APPEND);
    " > /dev/null 2>/dev/null
}
function get_all_func {
        #echo "<?include('$i');echo '#####';print_r(get_defined_vars());?>"|php5
    #TODO get all the functions,classes,user vars,superglobals
    php -r "include('$file');
        foreach(get_defined_functions() as \$row){
            file_put_contents('$FILE_NAME',\$row.'<br>',FILE_APPEND);
        }
    " > /dev/null 2>/dev/null
}
function get_included_files {
    php -r "include('$file');
        foreach(get_included_files() as \$row){
            file_put_contents('$FILE_NAME',\$row.'<br>',FILE_APPEND);
        }
    " > /dev/null 2>/dev/null
}
function get_constants {
    php -r "include('$file');
        \$a=get_defined_constants();
        if(isset(\$a['user']))
            \$a=\$a['user'];
        else
            \$a=array();
        \$isempty=0;
        foreach(\$a as \$row){
            file_put_contents('$FILE_NAME',\$row.'<br>',FILE_APPEND);
            \$isempty=1;
        }
        if(\$isempty==0)
            file_put_contents('$FILE_NAME','None<br>',FILE_APPEND);
    " > /dev/null 2>/dev/null
}
function get_user_vars {
    php -r "
\$F=file_get_contents('$file');
    preg_match_all('/\\\$[A-Za-z0-9-_]+/',\$F, \$vars);
        \$isempty=0;
        foreach(array_unique(\$vars[0]) as \$row){
            file_put_contents('$FILE_NAME',\$row.'<br>',FILE_APPEND);
            \$isempty=1;
        }
        if(\$isempty==0)
            file_put_contents('$FILE_NAME','None<br>',FILE_APPEND);
    " > /dev/null 
}

for arg in $*
do
    if [ $enable_desc -eq 1 ]
    then
        description=`cat $arg`
        enable_desc=0
    fi
    if [ $enable_out_file -eq 1 ]
    then
        FILE_NAME=$arg
        enable_out_file=0
    fi
    if [ $arg == '--exvars' ]
    then
        exvars=1
    elif [ $arg == '--exfuncs' ]
    then
        exfuncs=1
    elif [ $arg == '--allfuncs' ]
    then
        allfuncs=1
    elif [ $arg == '--exvars' ]
    then
        exvars=1
    elif [ $arg == '--desc' ]
    then
        enable_desc=1
    elif [ $arg == '-o' ]
    then
        enable_out_file=1
    fi
done
cat template_head >$FILE_NAME
#generate body from here
if [ "$description" != "" ]
then
    echo "<h1>Description</h1>"$description"<hr />" >>$FILE_NAME
fi
for file in `find $1 -name '*.php'`
do
    echo '<h2>'$file'</h2>' >>$FILE_NAME
    if [ $exfuncs -eq 0 ]
    then
        echo '<h3>User functions</h3>' >>$FILE_NAME
        get_user_func $file
    fi
    echo '<h3>Included files</h3>' >>$FILE_NAME
    get_included_files $file
    echo '<h3>Constants</h3>' >>$FILE_NAME
    get_constants $file
    if [ $exvars -eq 0 ]
    then
        echo '<h3>User variables</h3>' >>$FILE_NAME
        get_user_vars $file
    fi
    if [ $allfuncs -eq 1 ]
    then
        echo '<h3>All functions</h3>' >>$FILE_NAME
        get_all_func $file
    fi
    echo "<hr />" >>$FILE_NAME
done
echo "</div></body></html>" >>$FILE_NAME
